apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-test
      version: blue
  template:
    metadata:
      labels:
        app: jenkins-test
        version: blue
    spec:
      containers:
        - name: jenkins-test
          image: khushi2803/jenkins-test:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 80
